module.exports = {
  botName: "E TECH OFC",
  ownerName: "MR EPHRAIM OFC",
  ownerNumber: "2347072956206",
  ownerNumbers: ["2347072956206", "2348108717744"],
  protectedNumbers: ["2347072956206", "2348108717744"],
  backupNumber: "2348108717744",
  ownerNumberProtection: true,
  botNumberProtection: true,
  antiDeleteOwner: true,
  antiBanOwner: true,
  antiKickOwner: true,
  prefix: ".",
  footer: "╭─〔 ⚔ E TECH OFC 〕─╮\\n│ 👨‍💻 Developer: *MR EPHRAIM OFC*\\n│ ⚡ Powered by *N TECH PRO*\\n╰────────────────────╯",\n  buttonFooter: "⚡ Powered by N TECH PRO",
  menuImage: "./assets/e-tech-ofc.png",
  aliveImage: "./assets/e-tech-ofc.png",
  sessionName: "session",
  tempDir: "temp",
  channelLink: "https://whatsapp.com/channel/0029VbCrylk2Q0MbaKpp16",
  channelInviteCode: "0029VbCrylk2Q0MbaKpp16",
  pairWebsite: "https://e-tech-ofc-pair-1.onrender.com",
  botLink: "https://e-tech-ofc-pair-1.onrender.com",
  api: {\n    chamindu: "https://api.chamindu.site/api/v1"\n  }\n}